### ISSUE TITLE
Compile Issue

### ISSUE THREAD

**Issue by FXUDarkNova** [ha5dzs/python-fiducial-tracker#1]
Hi I am trying to test your code but I get this error
  File "tracker_main.py", line 57, in <module>
    markers[i]["translation_fifo"] = deque(maxlen=markers[i]["fifo_length"])
TypeError: an integer is required

And I can't seem to work out how to fix it any ideas?

**Comment by ha5dzs** [comment]
Apologies, I never got a notification of this because I had a problem with the email.
Do you have the module `collections` installed?
